spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: ${SERVER_PORT:8083}
