CREATE TABLE enterprises (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100)  NOT NULL,
    phone_number VARCHAR(20),
    website      VARCHAR(255),
    email        VARCHAR(100)  NOT NULL,
    description  VARCHAR(500),
    CONSTRAINT uq_enterprises_email UNIQUE (email)
);

CREATE TABLE teams (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id BIGINT        NOT NULL,
    name          VARCHAR(100)  NOT NULL,
    description   VARCHAR(500),
    CONSTRAINT fk_teams_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprises (id)
);

CREATE INDEX idx_teams_enterprise_id ON teams (enterprise_id);

CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    email        VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE team_members (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_team_members_team FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE,
    CONSTRAINT fk_team_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    -- Prevents a user being assigned to the same team twice.
    -- The backing index also serves team_id lookups (leading column), so no separate team_id index is needed.
    CONSTRAINT uq_team_members_team_user UNIQUE (team_id, user_id)
);

CREATE INDEX idx_team_members_user_id ON team_members (user_id);
